# Generated by Django 6.0.7 on 2026-07-15 21:52
# Esqueleto que o Django vai criar


from django.db import migrations

def cadastrar_brinquedos_padrao(apps, schema_editor):
    # Buscamos o modelo de Brinquedo dinamicamente para evitar problemas de importação
    Brinquedo = apps.get_model('core', 'Brinquedo')

    # Lista com os brinquedos específicos que você deseja iniciar no banco
    brinquedos = [
        {"nome": "Urso de Pelúcia Gigante", "preco": 129.90, "estoque": 8},
        {"nome": "Lego Castelo Medieval", "preco": 349.99, "estoque": 3},
        {"nome": "Carrinho de Controle Remoto Veloz", "preco": 189.50, "estoque": 5},
        {"nome": "Boneca Articulada Realista", "preco": 99.00, "estoque": 12},
        {"nome": "Pista de Corrida Hot Loops", "preco": 219.90, "estoque": 4},
    ]

    # Salvando cada um deles no banco de dados real
    for b in brinquedos:
        Brinquedo.objects.create(
            nome=b["nome"],
            preco=b["preco"],
            estoque=b["estoque"]
        )

class Migration(migrations.Migration):

    dependencies = [
        # Isso garante que a tabela de Brinquedos já exista antes de tentarmos salvar os dados
        ('core', '0001_initial'), 
    ]

    operations = [
        migrations.RunPython(cadastrar_brinquedos_padrao),
    ]